#include "sc2api/sc2_api.h"

#include "Sc2Bindings.h"
using namespace sc2;
using namespace Sc2Bindings;
#include "UnitTypes.h"

bool Sc2UnitTypes::RefreshUnitTypeData(const ObservationInterface* obs, bool ShouldRefresh)
{
	obs->GetUnitTypeData(false);

	UnitTypesCached = true;
	return true;
}

const UnitTypeData Sc2UnitTypes::GetUnitTypeData(UnitTypeID typeId)
{
	if (UnitTypesCached)
	{
		return UnitTypeMap[typeId];
	}
	return UnitTypeData();
}

const float Sc2UnitTypes::GetUnitRadius(UnitTypeID typeId)
{
	auto ThisType = UnitSizes.find(typeId);
	if (ThisType != UnitSizes.end())
	{
		return ThisType->second;
	}
	return 0.0f;
}

const TilePosition Sc2UnitTypes::GetTileSize(UnitTypeID UnitType)
{
	float radius = GetUnitRadius(UnitType);
	return GetSizeFromRadius(radius);
}

void Sc2UnitTypes::SetupUnitRadius()
{
	UnitSizes[UNIT_TYPEID::TERRAN_ARMORY] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_AUTOTURRET] = 1;
	UnitSizes[UNIT_TYPEID::TERRAN_BANSHEE] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_BARRACKS] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_BARRACKSFLYING] = 1.75;
	UnitSizes[UNIT_TYPEID::TERRAN_BARRACKSREACTOR] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_BARRACKSTECHLAB] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_BATTLECRUISER] = 1.25;
	UnitSizes[UNIT_TYPEID::TERRAN_BUNKER] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_COMMANDCENTER] = 2.75;
	UnitSizes[UNIT_TYPEID::TERRAN_COMMANDCENTERFLYING] = 2.5;
	UnitSizes[UNIT_TYPEID::TERRAN_CYCLONE] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_ENGINEERINGBAY] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_FACTORY] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_FACTORYFLYING] = 1.625;
	UnitSizes[UNIT_TYPEID::TERRAN_FACTORYREACTOR] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_FACTORYTECHLAB] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_FUSIONCORE] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_GHOST] = 0.375;
	UnitSizes[UNIT_TYPEID::TERRAN_GHOSTACADEMY] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_HELLION] = 0.625;
	UnitSizes[UNIT_TYPEID::TERRAN_HELLIONTANK] = 0.625;
	UnitSizes[UNIT_TYPEID::TERRAN_LIBERATOR] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_LIBERATORAG] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_MARAUDER] = 0.5625;
	UnitSizes[UNIT_TYPEID::TERRAN_MARINE] = 0.375;
	UnitSizes[UNIT_TYPEID::TERRAN_MEDIVAC] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_MISSILETURRET] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_MULE] = 0.375;
	UnitSizes[UNIT_TYPEID::TERRAN_ORBITALCOMMAND] = 2.75;
	UnitSizes[UNIT_TYPEID::TERRAN_ORBITALCOMMANDFLYING] = 2.5;
	UnitSizes[UNIT_TYPEID::TERRAN_PLANETARYFORTRESS] = 2.75;
	UnitSizes[UNIT_TYPEID::TERRAN_RAVEN] = 0.625;
	UnitSizes[UNIT_TYPEID::TERRAN_REAPER] = 0.375;
	UnitSizes[UNIT_TYPEID::TERRAN_REFINERY] = 1.6875;
	UnitSizes[UNIT_TYPEID::TERRAN_SCV] = 0.375;
	UnitSizes[UNIT_TYPEID::TERRAN_SENSORTOWER] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_SIEGETANK] = 0.875;
	UnitSizes[UNIT_TYPEID::TERRAN_SIEGETANKSIEGED] = 0.875;
	UnitSizes[UNIT_TYPEID::TERRAN_STARPORT] = 1.8125;
	UnitSizes[UNIT_TYPEID::TERRAN_STARPORTFLYING] = 1.625;
	UnitSizes[UNIT_TYPEID::TERRAN_STARPORTREACTOR] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_STARPORTTECHLAB] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_SUPPLYDEPOT] = 1.25;
	UnitSizes[UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED] = 1.25;
	UnitSizes[UNIT_TYPEID::TERRAN_THOR] = 1;
	UnitSizes[UNIT_TYPEID::TERRAN_THORAP] = 1;
	UnitSizes[UNIT_TYPEID::TERRAN_VIKINGASSAULT] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_VIKINGFIGHTER] = 0.75;
	UnitSizes[UNIT_TYPEID::TERRAN_WIDOWMINE] = 0.5;
	UnitSizes[UNIT_TYPEID::TERRAN_WIDOWMINEBURROWED] = 0.5;
	UnitSizes[UNIT_TYPEID::TERRAN_KD8CHARGE] = 0.5;
	UnitSizes[UNIT_TYPEID::TERRAN_POINTDEFENSEDRONE] = 0.625;
	UnitSizes[UNIT_TYPEID::TERRAN_REACTOR] = 1.125;
	UnitSizes[UNIT_TYPEID::TERRAN_TECHLAB] = 1.125;
	UnitSizes[UNIT_TYPEID::ZERG_BANELING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_BANELINGBURROWED] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_BANELINGCOCOON] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_BANELINGNEST] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_BROODLING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_BROODLORD] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_BROODLORDCOCOON] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELINGMARINE] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELINGMARINESHIELD] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELINGZEALOT] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELINGZERGLING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_CHANGELINGZERGLINGWINGS] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_CORRUPTOR] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_CREEPTUMORBURROWED] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_DRONE] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_DRONEBURROWED] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_EGG] = 0.125;
	UnitSizes[UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_EXTRACTOR] = 1.6875;
	UnitSizes[UNIT_TYPEID::ZERG_GREATERSPIRE] = 1.125;
	UnitSizes[UNIT_TYPEID::ZERG_HATCHERY] = 2.75;
	UnitSizes[UNIT_TYPEID::ZERG_HIVE] = 2.75;
	UnitSizes[UNIT_TYPEID::ZERG_HYDRALISK] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_HYDRALISKBURROWED] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_HYDRALISKDEN] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_INFESTATIONPIT] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_INFESTEDTERRANSEGG] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_INFESTOR] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_INFESTORBURROWED] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_INFESTORTERRAN] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_LAIR] = 2.75;
	UnitSizes[UNIT_TYPEID::ZERG_LARVA] = 0.125;
	UnitSizes[UNIT_TYPEID::ZERG_LOCUSTMP] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_LOCUSTMPFLYING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_LURKERDENMP] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_LURKERMP] = 0.9375;
	UnitSizes[UNIT_TYPEID::ZERG_LURKERMPBURROWED] = 0.75;
	UnitSizes[UNIT_TYPEID::ZERG_LURKERMPEGG] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_MUTALISK] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_NYDUSCANAL] = 1.125;
	UnitSizes[UNIT_TYPEID::ZERG_NYDUSNETWORK] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_OVERLORD] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_OVERLORDCOCOON] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_OVERLORDTRANSPORT] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_OVERSEER] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_QUEEN] = 0.875;
	UnitSizes[UNIT_TYPEID::ZERG_QUEENBURROWED] = 0.875;
	UnitSizes[UNIT_TYPEID::ZERG_RAVAGER] = 0.75;
	UnitSizes[UNIT_TYPEID::ZERG_RAVAGERCOCOON] = 0.75;
	UnitSizes[UNIT_TYPEID::ZERG_ROACH] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_ROACHBURROWED] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_ROACHWARREN] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_SPAWNINGPOOL] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_SPINECRAWLER] = 1.125;
	UnitSizes[UNIT_TYPEID::ZERG_SPINECRAWLERUPROOTED] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_SPIRE] = 1.125;
	UnitSizes[UNIT_TYPEID::ZERG_SPORECRAWLER] = 0.875;
	UnitSizes[UNIT_TYPEID::ZERG_SPORECRAWLERUPROOTED] = 0.5;
	UnitSizes[UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP] = 0.8125;
	UnitSizes[UNIT_TYPEID::ZERG_SWARMHOSTMP] = 0.8125;
	UnitSizes[UNIT_TYPEID::ZERG_TRANSPORTOVERLORDCOCOON] = 0.625;
	UnitSizes[UNIT_TYPEID::ZERG_ULTRALISK] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_ULTRALISKCAVERN] = 1.8125;
	UnitSizes[UNIT_TYPEID::ZERG_VIPER] = 1;
	UnitSizes[UNIT_TYPEID::ZERG_ZERGLING] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_ZERGLINGBURROWED] = 0.375;
	UnitSizes[UNIT_TYPEID::ZERG_PARASITICBOMBDUMMY] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_ADEPT] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_ADEPTPHASESHIFT] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_ARCHON] = 1;
	UnitSizes[UNIT_TYPEID::PROTOSS_ASSIMILATOR] = 1.6875;
	UnitSizes[UNIT_TYPEID::PROTOSS_CARRIER] = 1.25;
	UnitSizes[UNIT_TYPEID::PROTOSS_COLOSSUS] = 1;
	UnitSizes[UNIT_TYPEID::PROTOSS_CYBERNETICSCORE] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_DARKSHRINE] = 1.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_DARKTEMPLAR] = 0.375;
	UnitSizes[UNIT_TYPEID::PROTOSS_DISRUPTOR] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_DISRUPTORPHASED] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_FLEETBEACON] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_FORGE] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_GATEWAY] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_HIGHTEMPLAR] = 0.375;
	UnitSizes[UNIT_TYPEID::PROTOSS_IMMORTAL] = 0.75;
	UnitSizes[UNIT_TYPEID::PROTOSS_MOTHERSHIP] = 1.375;
	UnitSizes[UNIT_TYPEID::PROTOSS_NEXUS] = 2.75;
	UnitSizes[UNIT_TYPEID::PROTOSS_OBSERVER] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_ORACLE] = 0.75;
	UnitSizes[UNIT_TYPEID::PROTOSS_ORACLESTASISTRAP] = 0.4375;
	UnitSizes[UNIT_TYPEID::PROTOSS_PHOENIX] = 0.75;
	UnitSizes[UNIT_TYPEID::PROTOSS_PHOTONCANNON] = 1.125;
	UnitSizes[UNIT_TYPEID::PROTOSS_PROBE] = 0.375;
	UnitSizes[UNIT_TYPEID::PROTOSS_PYLON] = 1.125;
	UnitSizes[UNIT_TYPEID::PROTOSS_ROBOTICSBAY] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_SENTRY] = 0.5;
	UnitSizes[UNIT_TYPEID::PROTOSS_SHIELDBATTERY] = 1.125;
	UnitSizes[UNIT_TYPEID::PROTOSS_STALKER] = 0.625;
	UnitSizes[UNIT_TYPEID::PROTOSS_STARGATE] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_TEMPEST] = 1.25;
	UnitSizes[UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_VOIDRAY] = 1;
	UnitSizes[UNIT_TYPEID::PROTOSS_WARPGATE] = 1.8125;
	UnitSizes[UNIT_TYPEID::PROTOSS_WARPPRISM] = 0.875;
	UnitSizes[UNIT_TYPEID::PROTOSS_WARPPRISMPHASING] = 0.875;
	UnitSizes[UNIT_TYPEID::PROTOSS_ZEALOT] = 0.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_BATTLESTATIONMINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_COLLAPSIBLETERRANTOWERPUSHUNIT] = 2.75;
	UnitSizes[UNIT_TYPEID::NEUTRAL_DEBRISRAMPLEFT] = 2.9375;
	UnitSizes[UNIT_TYPEID::NEUTRAL_DEBRISRAMPRIGHT] = 2.9375;
	UnitSizes[UNIT_TYPEID::NEUTRAL_FORCEFIELD] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_LABMINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_LABMINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_MINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_MINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PROTOSSVESPENEGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PURIFIERMINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PURIFIERRICHMINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_PURIFIERVESPENEGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_RICHMINERALFIELD750] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_RICHVESPENEGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_SCANTIPEDE] = 0.375;
	UnitSizes[UNIT_TYPEID::NEUTRAL_SHAKURASVESPENEGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_SPACEPLATFORMGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_UNBUILDABLEBRICKSDESTRUCTIBLE] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_UNBUILDABLEPLATESDESTRUCTIBLE] = 1.125;
	UnitSizes[UNIT_TYPEID::NEUTRAL_VESPENEGEYSER] = 1.5;
	UnitSizes[UNIT_TYPEID::NEUTRAL_XELNAGATOWER] = 1.125;

}